# Generated by Django 5.1.7 on 2025-04-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementloyer',
            name='date_fin_avance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='mode_paiement',
            field=models.CharField(choices=[('espèce', 'Espèce'), ('mobile', 'Paiement mobile')], default='espèce', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='statut_paiement',
            field=models.CharField(choices=[('payé', 'Payé'), ('avance payée, pas caution', 'Avance payée, pas caution')], default='payé', max_length=30),
        ),
    ]
