# Generated by Django 5.1.7 on 2025-04-01 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_paiementloyer_date_fin_avance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementloyer',
            name='date_paiement',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure du paiement'),
        ),
    ]
