# Generated by Django 5.1.7 on 2025-04-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_paiementloyer_date_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementloyer',
            name='date_fin_avance',
        ),
    ]
