# Generated by Django 5.1.7 on 2025-04-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_paiementloyer_date_fin_avance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementloyer',
            name='statut_paiement',
            field=models.CharField(choices=[('confirmé', 'Confirmé'), ('en attente', 'En attente')], default='confirmé', max_length=30),
        ),
    ]
