# Generated by Django 5.1.7 on 2025-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_paiementloyer_statut_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementloyer',
            name='mode_paiement',
            field=models.CharField(choices=[('espèce', 'Espèce'), ('mobile', 'Paiement mobile')], default='espèce', max_length=50),
        ),
    ]
