# Generated by Django 5.1.7 on 2025-04-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_paiementloyer_mode_paiement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementloyer',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement de Loyer', 'verbose_name_plural': 'Paiements de Loyer'},
        ),
    ]
