# Generated by Django 5.1.7 on 2025-04-09 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_paiementloyer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='finlocation',
            name='Recu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='FinLocation/Recu/'),
        ),
        migrations.AddField(
            model_name='location',
            name='Recu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='location/Recu/'),
        ),
        migrations.AddField(
            model_name='paiementloyer',
            name='Recu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='Paiement/Recu/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_debut_location',
            field=models.DateField(verbose_name='Date de début de location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_fin_avance',
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin d'avance"),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_paiement',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image_contrat',
            field=models.ImageField(blank=True, help_text='Image du contrat de fin de location', null=True, upload_to='images/location/', verbose_name='Image du contrat'),
        ),
        migrations.AlterField(
            model_name='location',
            name='mode_paiement',
            field=models.CharField(choices=[('espèce', 'Espèce'), ('mobile', 'Paiement mobile')], default='espèce', max_length=50, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='location',
            name='montant_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Montant d'avance"),
        ),
        migrations.AlterField(
            model_name='location',
            name='montant_caution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la caution'),
        ),
        migrations.AlterField(
            model_name='location',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='location',
            name='nombre_mois_paye',
            field=models.IntegerField(default=0, verbose_name='Nombre de mois payé'),
        ),
        migrations.AlterField(
            model_name='location',
            name='statut_paiement',
            field=models.CharField(choices=[('payé', 'Payé'), ('avance payée, pas caution', 'Avance payée, pas caution')], default='payé', max_length=30, verbose_name='Statut du paiement'),
        ),
    ]
