# Generated by Django 5.1.7 on 2025-04-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_location_options_finlocation_recu_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Recu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='location_Recu/'),
        ),
    ]
