# Generated by Django 5.1.7 on 2025-04-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_location_recu_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finlocation',
            name='Recu_pdf',
        ),
        migrations.RemoveField(
            model_name='finlocation',
            name='etat_chambre_final',
        ),
    ]
