# Generated by Django 5.1.7 on 2025-04-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_message_group_receivers_message_is_group_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='maison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authentication.maison'),
        ),
    ]
