# Generated by Django 5.1.7 on 2025-05-03 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_message_maison'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietaire', to=settings.AUTH_USER_MODEL),
        ),
    ]
