# Generated by Django 5.1.7 on 2025-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_proprietaire_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finlocation',
            name='location',
        ),
        migrations.AddField(
            model_name='finlocation',
            name='location',
            field=models.ManyToManyField(related_name='fins_location', to='authentication.location'),
        ),
    ]
