# Generated by Django 5.1.7 on 2025-07-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_finlocation_location_finlocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
