# Generated by Django 5.1.7 on 2025-07-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_proprietaire_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='image',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='telephone',
        ),
    ]
