# Generated by Django 5.1.7 on 2025-07-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_proprietaire_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='adresse',
            field=models.CharField(default='Defaut', max_length=255),
        ),
    ]
