# Generated by Django 5.1.7 on 2025-07-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_maison_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='chambre_largeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chambre',
            name='chambre_longueur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chambre',
            name='largeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chambre',
            name='longueur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chambre',
            name='salon_largeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chambre',
            name='salon_longueur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='surface',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
