# Generated by Django 5.1.7 on 2025-07-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_chambre_chambre_largeur_chambre_chambre_longueur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='chambre_largeur',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='chambre_longueur',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='largeur',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='longueur',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='salon_largeur',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='salon_longueur',
        ),
        migrations.AlterField(
            model_name='chambre',
            name='surface',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
