# Generated by Django 5.1.7 on 2025-07-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_chambre_chambre_largeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typechambre',
            name='piece',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
