# Generated by Django 5.1.7 on 2025-07-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_typechambre_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typechambre',
            name='piece',
        ),
    ]
