# Generated by Django 5.1.7 on 2025-10-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_message_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
